In [1]:
from utz import *

In [2]:
os = read_parquet('data/2020/NewJersey2020Occupants.pqt')
os

,Year,County Code,Municipality Code,Department Case Number,Vehicle Number,Occupant Number,Physical Condition,Position In/On Vehicle,Ejection Code,Age,Sex,Location of Most Severe Injury,Type of Most Severe Phys Injury,Refused Medical Attention,Safety Equipment Available,Safety Equipment Used,Airbag Deployment,Hospital Code
0,2020,01,01,2020-020639,1,1,,01,01,26,F,,,,11,04,,
1,2020,01,01,2020-020639,2,2,,01,01,25,F,,,,11,04,,
2,2020,01,01,2020-021265,1,1,,01,01,74,M,,,,11,04,,
3,2020,01,01,2020-021265,1,2,,03,01,71,F,,,,11,04,,
4,2020,01,01,2020-021265,1,3,,06,01,44,M,,,,11,04,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
424962,2020,21,23,B150-2020-00361A,1,1,05,01,01,62,M,,,,11,04,,
424963,2020,21,23,B150-2020-00369A,1,1,05,01,01,63,M,,,,11,04,,
424964,2020,21,23,B150-2020-00369A,1,2,05,03,01,64,F,,,,11,04,,
424965,2020,21,23,B150-2020-00383A,1,1,05,01,01,37,M,,,01,11,04,,
424966,2020,21,23,B150-2020-00383A,2,2,03,01,01,68,M,08,04,01,11,04,,

In [3]:
ps = read_parquet('data/2020/NewJersey2020Pedestrians.pqt')
ps

,Year,County Code,Municipality Code,Department Case Number,Pedestrian Number,Physical Condition,Address City,Address State,Address Zip,Date of Birth,Age,Sex,Alcohol Test Given,Alcohol Test Type,Alcohol Test Results,Charge 1,Summons 1,Charge 2,Summons 2,Charge 3,Summons 3,Charge 4,Summons 4,Multi Charge Flag,Traffic Controls,Contributing Circumstances 1,Contributing Circumstances 2,Direction of Travel,Pre-Crash Action,Location of Most Severe Injury,Type of Most Severe Phys Injury,Refused Medical Attention,Safety Equipment Used,Hospital Code,Physical Status 1,Physical Status 2,Is Bicyclist?,Is Other?
0,2020,01,01,I-2020-005330,1,02,PHILADELPHIA,PA,19121,10/14/1946,73,M,,,,,,,,,,,,,04,73,,,33,01,02,02,,5101,01,,False,False
1,2020,01,01,I-2020-011440,1,04,CAMDEN,NJ,08030,07/03/1980,39,M,,,,,,,,,,,,,04,25,,,34,07,08,02,,5101,01,,False,False
2,2020,01,02,2001-0032,1,04,ATLANTIC CITY,NJ,08401,05/02/1987,32,M,N,,,,,,,,,,,,04,72,,03,42,06,08,02,,5101,01,,False,False
3,2020,01,02,2001-0062,31,,ATLANTIC CITY,NJ,08401,02/07/2006,13,M,N,,,,,,,,,,,,03,29,,00,29,,,,01,,00,,True,False
4,2020,01,02,2001-0233,1,03,ATLANTIC CITY,NJ,08401,08/09/2007,12,,N,,,,,,,,,,,,04,89,,04,44,07,07,02,,5101,00,,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5453,2020,21,21,2020-014845,1,01,ASBURY,NJ,08802,09/21/1954,66,F,N,,,39:4-34,011554,,,,,,,,11,73,89,01,42,09,03,02,01,99,00,,False,False
5454,2020,21,21,2020-016481,1,03,OXFORD,NJ,07863,11/29/1942,78,M,N,,,,,,,,,,,,03,75,,03,43,11,08,02,,7102,01,,False,False
5455,2020,21,22,2020-003616,31,05,WASHINGTON,NJ,07882,,59,M,N,,,,,,,,,,,,08,02,04,04,02,12,08,01,01,,01,,True,False
5456,2020,21,22,2020-005705,31,04,WASHINGTON,NJ,07882,09/23/2008,11,M,N,,,,,,,,,,,,04,02,14,03,16,11,08,01,08,,01,,True,False
5457,2020,21,23,B150-2020-00361A,1,01,BELVIDERE,NJ,07823,04/27/1964,56,M,Y,BR,0,,,,,,,,,,,,,,,12,07,,01,,,,False,False

In [4]:
from njdot.codes import *

In [5]:
def hist(df, code, desc=None):
    df = df.value_counts()
    if desc is None:
        df = df.sort_index()
    elif desc is False:
        pass
    elif desc is True:
        df = df.sort_values(ascending=False)
    else:
        raise
    if code:
        df.index = df.index.to_series().apply(lambda v: code[v])
    return df

## Occupant / Pedestrian Physical Conditions

In [6]:
och = hist(os['Physical Condition'], physical_condition)
och

                            152359
UNKNOWN                       5132
FATAL INJURY                   421
SUSPECTED SERIOUS INJURY      2354
SUSPECTED MINOR INJURY       19471
POSSIBLE INJURY              32675
NO APPARENT INJURY          212555
Name: Physical Condition, dtype: int64

In [7]:
pch = hist(ps['Physical Condition'], physical_condition)
pch

                             828
UNKNOWN                        9
FATAL INJURY                 190
SUSPECTED SERIOUS INJURY     550
SUSPECTED MINOR INJURY      1935
POSSIBLE INJURY             1662
NO APPARENT INJURY           284
Name: Physical Condition, dtype: int64

## Is Bicyclist / Is Other

In [8]:
pd.crosstab(ps['Is Bicyclist?'], ps['Is Other?'])

Is Other?      False  True
Is Bicyclist?
False           3508      3
True            1947      0

## Occupant / Pedestrian Most Severe Injury Type

In [9]:
ot = hist(os['Type of Most Severe Phys Injury'], injury_severity)
ot

                                 354614
Unknown                           16593
Amputation                          130
Concussion                          501
Internal                           1107
Bleeding                           5577
Contusion / Bruise / Abrasion      3984
Burn                                237
Fracture / Dislocation             1109
Complaint of Pain                 41115
Name: Type of Most Severe Phys Injury, dtype: int64

In [10]:
it = hist(ps['Type of Most Severe Phys Injury'], injury_severity)
it

                                 1197
Unknown                           154
Amputation                         13
Concussion                         71
Internal                          152
Bleeding                          678
Contusion / Bruise / Abrasion     794
Burn                                5
Fracture / Dislocation            309
Complaint of Pain                2085
Name: Type of Most Severe Phys Injury, dtype: int64

In [11]:
pys = hist(ps['Physical Status 1'], physical_status)
pys

                        1221
Unknown                  355
Apparently Normal       3645
Alcohol Use              150
Drug Use (Illicit)        13
Medication                 3
Alcohol and Drug Use      18
Physical Handicaps        21
Illness                    5
Fatigued                   1
Other                     26
Name: Physical Status 1, dtype: int64